### ISSUE TITLE
"Register a new application" section outdated

### ISSUE THREAD

**Issue by cesdperez** [spring-guides/gs-register-facebook-app#10]
I had to do some additional steps in order for [this guide](https://spring.io/guides/gs/accessing-facebook/) to work:

1. In my applicatoin pannel: add product -> Facebook login
2. Set `http://localhost:8080/connect/facebook` as a valid OAuth redirect URI

I can update the guide and send a pull request if you wish.

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
