### ISSUE TITLE
Demo fails when authenticating user.

### ISSUE THREAD

**Issue by tim93422** [spring-guides/gs-register-facebook-app#6]
When run with mvn spring-boot:run, the project currently fails when authenticating the user. Upgrading to the spring social facebook version 1.1.1.RELEASE fixes this. The updates necessitates a change to the path of the JsonProperty annotation to import com.fasterxml.jackson.annotation.JsonProperty.

macminis1:temp perry$ git clone https://github.com/spring-guides/gs-register-facebook-app.git
Cloning into 'gs-register-facebook-app'...
remote: Counting objects: 344, done.
remote: Total 344 (delta 0), reused 0 (delta 0), pack-reused 344
Receiving objects: 100% (344/344), 791.13 KiB | 514.00 KiB/s, done.
Resolving deltas: 100% (184/184), done.
Checking connectivity... done.
macminis1:temp perry$ cd gs-register-facebook-app/
macminis1:gs-register-facebook-app perry$ mvn spring-boot:run
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gs-register-facebook-app 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.2.5.RELEASE:run (default-cli) > test-compile @ gs-register-facebook-app >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gs-register-facebook-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/perry/temp/gs-register-facebook-app/src/main/resources
[INFO] skip non existing resourceDirectory /Users/perry/temp/gs-register-facebook-app/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gs-register-facebook-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/perry/temp/gs-register-facebook-app/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gs-register-facebook-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/perry/temp/gs-register-facebook-app/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ gs-register-facebook-app ---
[INFO] No sources to compile
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.2.5.RELEASE:run (default-cli) < test-compile @ gs-register-facebook-app <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.2.5.RELEASE:run (default-cli) @ gs-register-facebook-app ---
11:29:23.514 [hello.Application.main()] DEBUG o.s.web.client.RestTemplate - Created POST request for "https://graph.facebook.com/oauth/access_token"
11:29:23.517 [hello.Application.main()] DEBUG o.s.web.client.RestTemplate - Setting request Accept header to [application/x-www-form-urlencoded, multipart/form-data]
11:29:23.517 [hello.Application.main()] DEBUG o.s.web.client.RestTemplate - Writing [{client_id=[REDACTED], client_secret=[REDACTED], grant_type=[client_credentials]}] using [org.springframework.social.facebook.connect.FacebookOAuth2Template$1@3548e4d7]
11:29:23.887 [hello.Application.main()] DEBUG o.s.web.client.RestTemplate - POST request for "https://graph.facebook.com/oauth/access_token" resulted in 200 (OK)
11:29:23.888 [hello.Application.main()] DEBUG o.s.web.client.RestTemplate - Reading [org.springframework.util.MultiValueMap] as "text/plain;charset=UTF-8" using [org.springframework.social.facebook.connect.FacebookOAuth2Template$1@3548e4d7]
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.RunMojo$LaunchRunner.run(RunMojo.java:418)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.springframework.social.oauth2.AccessGrant.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Integer;)V
	at org.springframework.social.facebook.connect.FacebookOAuth2Template.postForAccessGrant(FacebookOAuth2Template.java:60)
	at org.springframework.social.oauth2.OAuth2Template.authenticateClient(OAuth2Template.java:197)
	at org.springframework.social.oauth2.OAuth2Template.authenticateClient(OAuth2Template.java:184)
	at hello.Application.fetchApplicationAccessToken(Application.java:34)
	at hello.Application.main(Application.java:16)
	... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.327 s
[INFO] Finished at: 2015-07-06T11:29:26-07:00
[INFO] Final Memory: 35M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.5.RELEASE:run (default-cli) on project gs-register-facebook-app: An exception occured while running. null: InvocationTargetException: org.springframework.social.oauth2.AccessGrant.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Integer;)V -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
macminis1:gs-register-facebook-app perry$

**Comment by gregturn** [comment]
Guide has been updated to proper version of Spring Social Facebook via https://github.com/spring-guides/gs-register-facebook-app/commit/d77da07ec348c2697a79a2f3aa79af211b788972
